sudo: required
dist: trusty
matrix:
  include:
    - script: make yabar
      compiler: gcc
      language: c
      env: CPPFLAGS=-DOLD_LIBCONFIG
      addons:
        apt:
          packages:
            - libxcb-randr0-dev
            - libconfig-dev
            - libcairo2-dev
            - libpango1.0-dev
            - libxcb-ewmh-dev
            - libxcb-icccm4-dev
            - libasound2-dev
            - libiw-dev
    - script: make docs
      language: generic
      addons:
        apt:
          packages:
            - docbook-xml
            - asciidoc
            - xsltproc
            - libxml2-utils
